version: 2.1

# Anchors in case we need to override the defaults from the orb
#baselibs_version: &baselibs_version v8.19.0
#bcs_version: &bcs_version v12.0.0

orbs:
  ci: geos-esm/circleci-tools@5

workflows:
  build-test:
    jobs:
      # We are turning off the GEOSgcm build and test for now, as the release/MAPL-v3
      # branch in GEOSgcm is still based on v11, but the FV3 code in this repo is now based
      # on v12. Once GEOSgcm MAPL3 is updated to v12, we can re-enable these tests.
      #########################################################################################
      # - ci/build:                                                                           #
      #     name: build-GEOSgcm-on-<< matrix.compiler >>                                      #
      #     context:                                                                          #
      #       - docker-hub-creds                                                              #
      #     matrix:                                                                           #
      #       parameters:                                                                     #
      #         compiler: [gfortran, ifort]                                                   #
      #     #baselibs_version: *baselibs_version                                              #
      #     repo: GEOSgcm                                                                     #
      #     checkout_fixture: true                                                            #
      #     mepodevelop: false                                                                #
      #     checkout_mapl3_release_branch: true                                               #
      #     persist_workspace: true # Needs to be true to run fv3/gcm experiment, costs extra #
      # - ci/run_fv3:                                                                         #
      #     name: run-FV3-on-<< matrix.compiler >>-with-GEOSgcm                               #
      #     context:                                                                          #
      #       - docker-hub-creds                                                              #
      #     matrix:                                                                           #
      #       parameters:                                                                     #
      #         compiler: [gfortran, ifort]                                                   #
      #     #baselibs_version: *baselibs_version                                              #
      #     requires:                                                                         #
      #       - build-GEOSgcm-on-<< matrix.compiler >>                                        #
      #     repo: GEOSgcm                                                                     #
      # # Run AMIP GCM (1 hour, no ExtData)                                                   #
      # - ci/run_gcm:                                                                         #
      #     name: run-GCM-on-<< matrix.compiler >>                                            #
      #     context:                                                                          #
      #       - docker-hub-creds                                                              #
      #     matrix:                                                                           #
      #       parameters:                                                                     #
      #         compiler: [gfortran, ifort]                                                   #
      #     requires:                                                                         #
      #       - build-GEOSgcm-on-<< matrix.compiler >>                                        #
      #     repo: GEOSgcm                                                                     #
      #     #baselibs_version: *baselibs_version                                              #
      #     #bcs_version: *bcs_version                                                        #
      #########################################################################################
      - ci/build:
          name: build-GEOSfvdycore-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>
          context:
            - docker-hub-creds
          matrix:
            parameters:
              compiler: [ifort, gfortran]
              fv_precision: ["R4", "R8"]
          #baselibs_version: *baselibs_version
          repo: GEOSfvdycore
          checkout_fixture: true
          # V12 code uses a special branch for now.
          fixture_branch: feature/sdrabenh/gcm_v12
          mepodevelop: false
          checkout_mapl3_release_branch: true
          persist_workspace: true # Needs to be true to run fv3/gcm experiment, costs extra
      # We also turn off the FV3 dycore runs for now
      #############################################################################################
      # - ci/run_fv3:                                                                             #
      #     name: run-FV3-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>-with-GEOSfvdycore #
      #     context:                                                                              #
      #       - docker-hub-creds                                                                  #
      #     matrix:                                                                               #
      #       parameters:                                                                         #
      #         compiler: [gfortran, ifort]                                                       #
      #         fv_precision: ["R4", "R8"]                                                        #
      #     #baselibs_version: *baselibs_version                                                  #
      #     requires:                                                                             #
      #       - build-GEOSfvdycore-as-<< matrix.fv_precision >>-on-<< matrix.compiler >>          #
      #     repo: GEOSfvdycore                                                                    #
      #############################################################################################
